spring:
  data:
    mongodb:
      uri: mongodb://testuser:e2VdOav40i@39.106.9.158:28001/test


# Redis
redis:
  ip: 123.56.216.212
  port: 6666
  pool:
    maxActive:  1024
    maxIdle: 200
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: true
    password: RH06863b3e6


rocketMQ:
  namesrvAddr: 123.56.216.212:5555

