spring:
  data:
    mongodb:
      uri: mongodb://testuser:e2VdOav40i@39.106.9.158:28001/test
  redis:
    database: 0  
    # Redis服务器地址
    hostName: 123.56.216.212
    # Redis服务器连接端口
    port: 6666
    # Redis服务器连接密码（默认为空）
    password: RH06863b3e6
    pool:
      jedis:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000



rocketMQ:
  namesrvAddr: 123.56.216.212:5555

hyjf:
  activity:
    888:
      id: 37
    regist:
      tzj:
        id: 39

am:
  config:
    service:
      name: AM-CONFIG
  user:
    service:
      name: AM-USER
  trade:
    service:
      name: AM-TRADE

hyjf:
  env:
    test : true

sms:
  send:
    title: 【汇盈金服】
    suffix: 回复TD退订
    url: http://sh999.eucp.b2m.cn:8080/sdkproxy/sendsms.action
    #软件序列号
    softSerialNo: 9SDK-EMY-0999-JBVLP
    key: 286141
    market:
      url: http://sdk4rptws.eucp.b2m.cn:8080/sdkproxy/sendsms.action
      softSerialNo: 6SDK-EMY-6688-JCQTL
      key: 756526