spring:
  # Redis 
  redis:
    #数据库索引
    database: 0
    # Redis服务器地址
    host: 123.56.216.212
    # Redis服务器连接端口
    port: 6666
    # Redis服务器连接密码（默认为空）
    password: RH06863b3e6
    pool:
      jedis:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000

rocketMQ:
  #namesrvAddr: ${rocketMQ.namesrvAddr}
  namesrvAddr: 123.56.216.212:5555


mybatis:
  mapper-locations: classpath:com/hyjf/am/user/dao/mapper/xml/**/*.xml






#多数据源 1主2从
datasource:
 #从库数量
  readSize: 2
   # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
#主库
  write:
    url: jdbc:mysql://123.56.216.212:7777/hyjf_user?useUnicode=true&characterEncoding=utf-8
    username: hyjf_developer
    password: QD@hyjfdev2000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  read1:
    url: jdbc:mysql://123.56.216.212:7777/hyjf_user?useUnicode=true&characterEncoding=utf-8
    username: hyjf_developer
    password: QD@hyjfdev2000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  read2:
    url: jdbc:mysql://123.56.216.212:7777/hyjf_user?useUnicode=true&characterEncoding=utf-8
    username: hyjf_developer
    password: QD@hyjfdev2000
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
