rocketMQ:
  #namesrvAddr: ${rocketMQ.namesrvAddr}
  namesrvAddr: 123.56.216.212:5555
  group :
    couponGroup : COUPON_GROUP
    smsCodeGroup : SMS_CODE_GROUP
  topic :
    couponTopic : COUPON_TOPIC
    smsCodeTopic : SMS_CODE_TOPIC
  tag :
    defaultTag : HYJF_DEFAULT_TAG

