
# turbine 配置
turbine:
  app-config: zuul,cs-message,cs-user,cs-market,cs-trade,pay
  aggregator:
    # turbine聚集数据的粒度
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host-port: true
  instanceUrlSuffix:
    # turbine连接hystrix-dashboard的url
    default: actuator/hystrix.stream