basic:
  auth:
    username: hyjf
    password: hyjf123


ignore:
  urls:
    app:
      key: /server/getBestServerAction,
      user: /smsCode/send,/user/register,/user/login
    web: /smsCode/send,/user/register,/user/login
    wechat: /smsCode/send,/user/register,/user/login
    api: /smsCode/send,/user/register,/user/login