# Redis
redis:
  ip: 123.56.216.212
  port: 6666
  pool:
    maxActive:  1024
    maxIdle: 200
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: true
    password: RH06863b3e6

basic:
  auth:
    username: hyjf
    password: hyjf123

ignore:
  urls:
    app:
      key: /server/getBestServerAction,
      user: /smsCode/send,/user/register,/user/login
    web: /smsCode/send,/user/register,/user/login,/user/password/checkpassword
    wechat: /smsCode/send,/user/register,/user/login
    api: /smsCode/send,/user/register,/user/login


hyjf:
  domain:
    name: hyjf.com,huiyingdai.com