quartz:
  threadPool:
    threadCount: 10
  dataSource:
    quartzDataSource:
      URL: jdbc:mysql://123.56.216.212:7777/batch
      user: hyjf_developer
      password: QD@hyjfdev2000
      maxConnections: 10

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
  resources:
    static-locations: classpath:/static/