#spring:
#  application:
#    name: zipkin-server
#  sleuth:
#    enabled: false
#    sampler:
#      percentage: 1.0
#  #kafka config
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: 123.56.216.212:9092
#          zkNodes: 123.56.216.212:2181
#
#server:
#  port: 9411
#
##elasticsearch config
#zipkin:
#  storage:
#    type: elasticsearch
#    elasticsearch:
#      hosts: 123.56.216.212:9200
#      cluster: elasticsearch
#      index: zipkin
#      index-shards: 1
#      index-replicas: 1
#
#logging:
#  path: zipkin-server.log