spring:
  application:
    name: eureka-server

server:
  port: 1111
eureka:
  instance:
    hostname: microserver1
  environment: ${spring.profiles.active}
  datacenter: Main
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://microserver2:1111/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: eureka.log
  file.max-size: 100MB

info:
  name: ${spring.profiles.active}
  version: '@project.version@'
  encoding: '@project.build.sourceEncoding@'
  java:
    version: '@java.version@'