spring:
  application:
    name: eureka-server  
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: '@spring.boot.admin.url@'
        username: '@spring.boot.admin.username@'
        password: '@spring.boot.admin.password@'
server:
  port: 1111
eureka:
  environment: ${spring.profiles.active}
  datacenter: Main
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: '@eureka.serviceUrl.default@'


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: eureka.log
  file.max-size: 100MB