# Redis
redis:
  ip: 123.56.216.212
  port: 6666
  pool:
    maxActive:  1024
    maxIdle: 200
    maxWait: 10000
    testOnBorrow: true
    testOnReturn: true
    password: RH06863b3e6


# 没有密码？？ namesrvAddr: ${rocketMQ.namesrvAddr}
rocketMQ:
  namesrvAddr: 123.56.216.212:5555

am:
  config:
    service:
      name: http://AM-CONFIG/am-config
  user:
    service:
      name: http://AM-USER/am-user
  trade:
    service:
      name: http://AM-TRADE/am-trade
  market:
    service:
      name: http://AM-MARKET/am-market
  dataCollect:
    service:
      name: http://AM-STATISTICS/am-statistics